security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'




    providers:
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: email




    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false




        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: _username
              
               
                password_parameter: _password
                default_target_path: admin_dashboard
            logout:
                path: logout
                target: /


                 

            login_throttling:
                max_attempts: 5


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }











