# config/services.yaml

parameters:

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les commandes, events, etc.

    # Rend les classes du dossier src/ disponibles comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration explicite du service Firebase
    App\Service\FirebaseService:
        public: true

